# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      # - image: circleci/golang:1.8
      - image: vvakame/circleci-gaego
        environment:
            TZ: "/usr/share/zoneinfo/Asia/Tokyo"

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/mstssk/mstssk.jp
    steps:
      # Checkout with cache https://circleci.com/docs/2.0/caching/#source-caching
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - checkout
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      # specify any bash command here prefixed with `run: `
      # - run: go get -v -t -d ./...
      # - run: go test -v ./...
      - run:
          name: show env
          command: date && echo $GOPATH && gcloud version
      # gcloudコマンドはdockerイメージに持った最新版を使用する。問題が発生した場合は↓コマンドでバージョンを固定する
      # - run: gcloud --quiet components update --version 179.0.0

      - run:
          name: go_appengine_sdk
          command: |
            rm -rf /work/go_appengine &&
            curl -o /work/go_appengine_sdk_linux_amd64.zip https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.60.zip &&
            unzip -q -d /work /work/go_appengine_sdk_linux_amd64.zip

      - run: ./setup.sh
      - run: ./test.sh
