runtime: go
api_version: go1

handlers:
- url: (.*)/
  static_files: public\1/index.html
  upload: public(.*)/index.html
  secure: always
- url: /(.*)
  static_files: public/\1
  upload: public/(.*)
  secure: always
- url: /.*
  script: _go_app
  secure: always
