runtime: go
api_version: go1.8

handlers:
- url: /api/admin/.*
  script: _go_app
  secure: always
  login: admin
- url: /api/.*
  script: _go_app
  secure: always
- url: (.*)/
  static_files: public\1/index.html
  upload: public(.*)/index.html
  secure: always
- url: /(.*)
  static_files: public/\1
  upload: public/(.*)
  secure: always
- url: /.*
  script: _go_app
  secure: always
